name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - ci/setup

  workflow_dispatch:
    inputs:
      module:
        description: "Which module to test?"
        required: true
        default: all
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - data_research
          - visualization

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Cache dataset
        uses: actions/cache@v5
        id: dataset-cache
        with:
          path: ./data
          key: dataset-v1

      - name: Download dataset
        if: steps.dataset-cache.outputs.cache-hit != 'true'
        run: uv run python -m utils download

      - name: Run module
        run: |
          MODULE="${{ github.event.inputs.module || 'all' }}"
          if [ "$MODULE" = "all" ]; then
            uv run python -m analytics data-quality --input ./data/dataset.parquet
            uv run python -m analytics data-research --input ./data/dataset.parquet
            uv run python -m analytics data-visualize --input ./data/dataset.parquet
          else
            uv run python -m analytics "$MODULE" --input ./data/dataset.parquet
          fi