name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - ci/setup

  workflow_dispatch:
    inputs:
      module:
        description: "Which module to test?"
        required: true
        default: all
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - data_research
          - visualization

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Print selected module
        run: |
          echo "Selected module: ${{ github.event.inputs.module }}"