name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - ci/setup

  workflow_dispatch:
    inputs:
      module:
        description: "Which module to test?"
        required: true
        default: all
        type: choice
        options:
          - all
          - data_quality
          - data_research
          - visualization

jobs:
  prepare-data:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v5
      - run: pip install uv
      - run: uv sync
      - uses: actions/cache@v5
        id: dataset-cache
        with:
          path: ./data
          key: dataset-v1
      - name: Download dataset
        if: steps.dataset-cache.outputs.cache-hit != 'true'
        run: uv run python -m utils download

  test-module:
    needs: prepare-data
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src

    strategy:
      matrix:
        module:
          - name: data_quality
            command: data-quality
          - name: data_research
            command: data-research
          - name: visualization
            command: data-visualize

    steps:
      - uses: actions/checkout@v5
      - run: pip install uv
      - run: uv sync
      - uses: actions/cache@v5
        with:
          path: ./data
          key: dataset-v1
      - name: Run ${{ matrix.module.name }}
        if: >-
          github.event.inputs.module == 'all' ||
          github.event.inputs.module == '' ||
          github.event.inputs.module == matrix.module.name
          

        run: uv run python -m analytics ${{ matrix.module.command }} --input ./data/dataset.parquet

      - name: Upload figures
        if: matrix.module.name == 'visualization'
        uses: actions/upload-artifact@v5
        with:
          name: figures
          path: reports/figures/

  deploy-pages:
    needs: test-module
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v5

      # Copy the committed index.html as the site base
      - name: Prepare site
        run: |
          mkdir -p ./site
          cp pages/index.html ./site/index.html

      # Download plots into site/figures/
      - name: Download figures
        uses: actions/download-artifact@v5
        with:
          name: figures
          path: ./site/figures

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4